# Generated by Django 2.1.5 on 2019-02-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190209_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
