# Generated by Django 2.1.5 on 2019-02-19 11:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190209_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('media_url', models.URLField(max_length=1000)),
                ('media_type', models.IntegerField(default=None, null=True)),
                ('choice_type', models.IntegerField(default=1, null=True)),
                ('hints', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'choices',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('icon_url', models.URLField(max_length=1000, null=True)),
                ('iamge_url', models.URLField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CourseSubjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flag', models.BooleanField(default=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Courses')),
            ],
            options={
                'db_table': 'course_subjects',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('question_type', models.IntegerField(default=None, null=True)),
                ('hints', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionsChoices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flag', models.BooleanField(default=True)),
                ('choice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Choices')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Questions')),
            ],
            options={
                'db_table': 'questions_choices',
            },
        ),
        migrations.CreateModel(
            name='QuestionsSubject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flag', models.BooleanField(default=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Questions')),
            ],
            options={
                'db_table': 'questions_subject',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('icon_url', models.URLField(max_length=1000, null=True)),
                ('iamge_url', models.URLField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.AddField(
            model_name='questionssubject',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subjects'),
        ),
        migrations.AddField(
            model_name='coursesubjects',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subjects'),
        ),
        migrations.AlterUniqueTogether(
            name='coursesubjects',
            unique_together={('course_id', 'subject_id')},
        ),
    ]
