# Generated by Django 2.1.5 on 2019-02-21 09:38

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190219_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quiz_type', models.CharField(max_length=9)),
                ('marks', models.FloatField()),
                ('percentage', models.FloatField()),
                ('status', models.IntegerField()),
                ('questions_attempted', models.IntegerField(default=0)),
                ('correct_questions', models.IntegerField(default=0)),
                ('incorrect_questions', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('result_set', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_id', models.IntegerField(default=None)),
                ('entity_type', models.CharField(default=None, max_length=255)),
                ('flag', models.IntegerField()),
            ],
            options={
                'db_table': 'quiz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_answer', models.IntegerField(default=None)),
                ('correct_answer', models.IntegerField()),
                ('marks', models.FloatField(default=0.0)),
                ('response_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.IntegerField()),
            ],
            options={
                'db_table': 'quiz_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSubjectScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subjects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subject_score',
            },
        ),
    ]
