# Generated by Django 2.1.5 on 2019-02-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_quiz_quizquestions_usersubjectscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionschoices',
            old_name='choice_id',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='questionschoices',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionssubject',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionssubject',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
