# Generated by Django 2.1.5 on 2019-02-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_questionssubject_is_correct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizquestions',
            options={},
        ),
    ]
