# Generated by Django 2.1.5 on 2019-02-22 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190221_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='status',
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Questions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='correct_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='correct_answer', to='api.Choices'),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='flag',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='user_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_answer', to='api.Choices'),
        ),
    ]
