# Generated by Django 2.1.5 on 2019-02-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190222_0421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'managed': True},
        ),
    ]
