# Generated by Django 2.1.5 on 2019-02-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190222_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='media_type',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='media_url',
            field=models.URLField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
