# Generated by Django 2.1.5 on 2019-02-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190222_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='media_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
