# Generated by Django 2.1.5 on 2019-02-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190222_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='media_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
