# Generated by Django 2.1.5 on 2019-02-22 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190222_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestions',
            name='correct_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='correct_answer', to='api.Choices'),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='user_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_answer', to='api.Choices'),
        ),
    ]
