# Generated by Django 2.1.5 on 2019-02-25 07:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20190222_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSubject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flag', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'paper_subjects',
            },
        ),
        migrations.CreateModel(
            name='PracticePapers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('time_limit', models.IntegerField()),
                ('is_time_per_question', models.BooleanField(default=False)),
                ('guidelines', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'practice_papers',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('flag', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question_bank',
            },
        ),
        migrations.CreateModel(
            name='QuestionsQuestionBank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Questions')),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.QuestionBank')),
            ],
            options={
                'db_table': 'question_question_bank',
            },
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.DateField()),
                ('academic_year_start', models.DateField()),
                ('academic_year_end', models.DateField()),
            ],
            options={
                'db_table': 'years',
            },
        ),
        migrations.AddField(
            model_name='practicepapers',
            name='question_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.QuestionBank'),
        ),
        migrations.AddField(
            model_name='practicepapers',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Years'),
        ),
        migrations.AddField(
            model_name='papersubject',
            name='practice_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PracticePapers'),
        ),
        migrations.AddField(
            model_name='papersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subjects'),
        ),
    ]
