# Generated by Django 2.1.5 on 2019-02-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190225_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicepapers',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
