# Generated by Django 2.1.5 on 2019-02-26 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_practicepapers_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPracticePaperScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.BooleanField(default=True)),
                ('practice_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PracticePapers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_practice_paper_score',
            },
        ),
        migrations.AlterField(
            model_name='usersubjectscore',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
