# Generated by Django 2.1.5 on 2019-02-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190226_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
