# Generated by Django 2.1.5 on 2019-02-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20190226_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicepapers',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
