# Generated by Django 2.1.5 on 2019-02-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190226_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
