# Generated by Django 2.1.5 on 2019-03-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20190302_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
