# Generated by Django 2.1.5 on 2019-04-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_userdevices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdevices',
            options={'managed': False},
        ),
    ]
